spring:
  datasource:
    url: jdbc:mysql://mysql:3306/aiview?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: aiview
    password: aiview
  data:
    redis:
      host: redis
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672