CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL DEFAULT '',
    avatar VARCHAR(255) DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS user_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL UNIQUE,
    skill_profile JSON DEFAULT NULL,
    weak_topics JSON DEFAULT NULL,
    interview_count INT NOT NULL DEFAULT 0,
    avg_score DECIMAL(5, 2) NOT NULL DEFAULT 0,
    best_score INT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES app_user (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS knowledge_point (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    parent_id BIGINT DEFAULT NULL,
    topic VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    difficulty TINYINT NOT NULL DEFAULT 1 COMMENT '1初级 2中级 3高级',
    description VARCHAR(500) DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_kp_parent FOREIGN KEY (parent_id) REFERENCES knowledge_point (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS question (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    knowledge_point_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    difficulty TINYINT NOT NULL DEFAULT 1,
    source VARCHAR(20) NOT NULL DEFAULT 'SYSTEM' COMMENT 'SYSTEM/AI',
    usage_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_question_kp FOREIGN KEY (knowledge_point_id) REFERENCES knowledge_point (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS interview_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    topic VARCHAR(30) NOT NULL,
    level VARCHAR(20) NOT NULL DEFAULT '中级' COMMENT '初级/中级/高级',
    status VARCHAR(20) NOT NULL DEFAULT 'START' COMMENT 'START/ASKING/WAITING_ANSWER/EVALUATING/FINISHED',
    current_question_id BIGINT DEFAULT NULL,
    question_count INT NOT NULL DEFAULT 0,
    total_score INT DEFAULT NULL,
    report JSON DEFAULT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES app_user (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS interview_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL COMMENT 'AI/USER',
    kind VARCHAR(20) NOT NULL COMMENT 'question/answer/feedback/followup/report',
    content TEXT NOT NULL,
    knowledge_point_id BIGINT DEFAULT NULL,
    scores JSON DEFAULT NULL COMMENT '四维评分: knowledge/expression/source/analysis',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_msg_session FOREIGN KEY (session_id) REFERENCES interview_session (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS interview_result (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    dimensions JSON NOT NULL,
    total_score INT NOT NULL,
    weak_points JSON DEFAULT NULL,
    suggestions JSON DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_result_session FOREIGN KEY (session_id) REFERENCES interview_session (id),
    CONSTRAINT fk_result_user FOREIGN KEY (user_id) REFERENCES app_user (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS knowledge_base (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) DEFAULT '',
    chunk_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_kb_user FOREIGN KEY (user_id) REFERENCES app_user (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS knowledge_chunk (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    kb_id BIGINT NOT NULL,
    title VARCHAR(200) DEFAULT '',
    content TEXT NOT NULL,
    embedding JSON DEFAULT NULL COMMENT 'embedding 向量，JSON 数组',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chunk_kb FOREIGN KEY (kb_id) REFERENCES knowledge_base (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;